services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    container_name: chat-backend

    env_file:
      - .env

    expose:
      - "5001"

    restart: unless-stopped

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:5001/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    
    container_name: chat-frontend

    ports:
      - "80:80"

    depends_on:
      backend:
        condition: service_healthy

    restart: unless-stopped

